services:
  shop-db:
    image: postgres:16.1-alpine
    container_name: shop-postgres-db
    restart: always
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - shop-postgres-db-data:/var/lib/postgresql/data
      - ./data-samples/init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh
  shop-service-1:
    build: ./src/shop-service/
    container_name: shop-service-1
    hostname: shop-service-1
    restart: on-failure
    env_file:
      - .env
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: prod
      CATEGORIES_SCHEDULER_CRON: 0 */10 * * * *
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      shop-db:
        condition: service_healthy
  shop-service-2:
    build: ./src/shop-service/
    container_name: shop-service-2
    hostname: shop-service-2
    restart: on-failure
    env_file:
      - .env
    environment:
      SERVER_PORT: 8081
      SPRING_PROFILES_ACTIVE: prod
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      shop-db:
        condition: service_healthy
  shop-service-3:
    build: ./src/shop-service/
    container_name: shop-service-3
    hostname: shop-service-3
    restart: on-failure
    env_file:
      - .env
    environment:
      SERVER_PORT: 8082
      SPRING_PROFILES_ACTIVE: prod
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      shop-db:
        condition: service_healthy
  user-service:
    build: ./src/user-service/
    container_name: user-service
    hostname: user-service
    restart: on-failure
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      shop-db:
        condition: service_healthy
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file:
      - .env
    depends_on:
      shop-db:
        condition: service_healthy
    volumes:
      - ./pgadmin/pgadmin_setup.json:/pgadmin4/servers.json:ro
  nginx-gateway:
    image: nginx
    container_name: nginx-gateway
    restart: always
    ports:
      - "443:443"
    depends_on:
      pgadmin:
        condition: service_started
      shop-service-1:
        condition: service_healthy
      shop-service-2:
        condition: service_healthy
      shop-service-3:
        condition: service_healthy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/static:/data/www/static:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
volumes:
  shop-postgres-db-data:
