services:
  shop-db:
    image: postgres:16.1-alpine
    container_name: shop-postgres-db
    restart: on-failure
    env_file:
      - .env
    ports:
      - "${POSTGRESQL_EXT_PORT}:${POSTGRESQL_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - shop-postgres-db-data:/var/lib/postgresql/data
  shop:
    build: ./
    container_name: shop-backend
    hostname: shop
    restart: on-failure
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      DB_HOST: shop-db
      SERVER_PORT: 8080
    depends_on:
      shop-db:
        condition: service_healthy
volumes:
  shop-postgres-db-data: